// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbrrfqxkvnrailnwfzif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpicnJmcXhrdm5yYWlsbndmemlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODUxNzAsImV4cCI6MjA3MTg2MTE3MH0.jwIcaznVzFUt2yCNP55ZYB-C_KYUTCcM7pSvB_vVYAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});